### ISSUE TITLE
Incorrect pod version in documentation

### ISSUE THREAD

**Issue by horlann** [customerio/customerio-flutter#118]
I always get this error,when tried to update a pods

This problen was solved when I deleted version of pod

[!] CocoaPods could not find compatible versions for pod "CustomerIO/Tracking":
  In Podfile:
    customer_io (from `.symlinks/plugins/customer_io/ios`) was resolved to 1.3.2, which depends on
      CustomerIO/Tracking (~> 1.3.2)

   pod 'CustomerIO/MessagingPushFCM', ,'~> 3.1.2' =>
 pod 'CustomerIO/MessagingPushFCM',

None of your spec sources contain a spec satisfying the dependency: `CustomerIO/Tracking (~> 1.3.2)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by mrehan27** [comment]
Hi @horlann, thank you for reaching out and sharing this with us. I have noticed that the version fetching on our docs site is currently misbehaving, and we are actively working on a fix, which will be applied very soon. In the meantime, I can help you here to resolve the issue.

iOS V3 is not currently supported by our Flutter Package. You will need to continue using V2. Please update your Podfile as follows:

```
# Note: You may need to add this line, as required by FCM, to the top of your Podfile if you encounter errors during 'pod install'
use_frameworks! :linkage => :static

target 'YourApp' do # Look for the main app target. 
  # Make all file modifications after this line:
  config = use_native_modules!

  # Add the following line to add the Customer.io native dependency: 
  pod 'CustomerIO/MessagingPushFCM', '~> 2.13.0'
end

# Next, copy and paste the code below to the bottom of your Podfile: 
target 'NotificationServiceExtension' do
  pod 'CustomerIO/MessagingPushFCM', '~> 2.13.0'    
end
```

After updating, please run **Flutter Clean** and install the pods again by either using Flutter commands or by running the following directly in your project folder:

```
pod update --repo-update --project-directory=ios
```

This should resolve the issue for you. Apologies for the inconvenience this has caused. Please let us know if you have any more questions.

**Comment by horlann** [comment]
Thats didnt help.Im also facing with with problem
<img width="836" alt="image" src="https://github.com/customerio/customerio-flutter/assets/61031890/0d83d06a-89b3-437f-907c-c2b8da4fe841">

**Comment by mrehan27** [comment]
Sorry to hear the issue is still not resolved. This could be related to caching or dependencies not being fetched properly. Can you please try the following steps?

- Ensure the dependency is correctly listed in your `pubspec.yaml` file, or run `flutter pub add customer_io` again
- Clear caches and restart your IDE if you are using Android Studio
- Run Flutter Clean from Android Studio
- Run Flutter Pub Get from Android Studio
- Run `pod install --repo-update --project-directory=ios` in your terminal
- Run your app

These steps should help resolve the issue. If the problem persists, please let us know so we can further help you with debugging.
