### ISSUE TITLE
Have problem with Android notifications

### ISSUE THREAD

**Issue by damienissa** [customerio/customerio-flutter#26]
Hi, @Shahroz16. 
I have an issue when adding **DEEP LINK OR WEB URL**.
It is shown on iOS but not shown on Android.
I see that it received by FCM but not shown as Notification

**Comment by Shahroz16** [comment]
Hey @damienissa can you please give me details, are you using Rich push or custom payload?

**Comment by damienissa** [comment]
I'm using Rich push. If I didn't put **DEEP LINK OR WEB URL** it works fine. But when I set this property it does not show. maybe I miss something.

**Comment by Shahroz16** [comment]
Example [project](https://github.com/customerio/amiapp-flutter) is set up, and you can use it as a reference, we are just polishing it a bit more. 

Additional question, are you using any other push service? e.g flutter firebase etc? cause that can cause this issue too.

**Comment by damienissa** [comment]
Yes. I'm using FCM.

**Comment by Shahroz16** [comment]
Is there a specific reason you are using the flutter FCM SDK? I ask because then I can guide you accordingly. 

What the flutter FCM does is it overrides, the android service of our SDK. So if you are okay with removing it, all the push handling will be done via our SDK and everything should work. 

If you want to keep flutter FCM SDK but want our SDK to take over push, then you need to add these lines of code in your `Manifest.xml` file in android under the `<application>` tag.

```
<service
    android:name="io.customer.messagingpush.CustomerIOFirebaseMessagingService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```

In the future, we will be adding more flexibility as well, in case you want to use multiple push services.

**Comment by damienissa** [comment]
@Shahroz16 Yeah it helps. I spent all day finding solutions. Please add this to the documentation. It will help new developers setup their Flutter SDK.

**Comment by Shahroz16** [comment]
Apologies for the frustration it might have caused you, updating the docs and closing the ticket. Thank you for your patience.
