### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by Jethro87** [customerio/customerio-flutter#28]
It would be great if mac was supported, as I plan to release a Mac app quite soon. Thanks.

**Comment by StephMoreno** [comment]
Hi @Jethro87 

I'm one of the Product Managers here at Customer.io. Thanks for submitting this request as a future addition for us to look into! I have made an internal note for our team to keep this as an item of interest as we continue to evolve our product. 

I'll be closing this issue since it's been documented. Thanks so much for submitting your idea:)
