### ISSUE TITLE
When will web be supported?

### ISSUE THREAD

**Issue by Anderzzon** [customerio/customerio-flutter#93]
Are you currently working on support for Flutter for Web?

**Comment by ami-aman** [comment]
Hi @Anderzzon 

Thanks for reaching out!

I understand that you want us to support Flutter for web, but unfortunately we're not working on that right now. I've added your feature request to our list and upvoted it.

Since the request is logged internally, I'll close this ticket for now. I can't provide a timeline yet, but someone from the team will update you on the feature's progress on this thread. Please reopen the ticket if you have any other questions.

**Comment by AminSheikh** [comment]
We need support for flutter web too, is there any updates on this ? what are the blockers ? are there other workarounds ?
